---

name: release
on:    # yamllint disable-line rule:truthy
  - push
permissions:
  contents: write
jobs:

  release:
    name: Make/Update a release from push
    runs-on: ubuntu-latest
    outputs:
      BINARY_NAME: ${{ steps.variables.outputs.BINARY_NAME }}
    steps:
      - name: Wait build-test-push success
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: build-test-push
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parse Changelog
        id: changelog
        uses: ocavue/changelog-parser-action@v1
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-test-push.yml
      - name: Show files
        run: ls -lh
      - name: Set up binary name based on a release version
        id: variables
        run: |
          (
            if [[ "${{ steps.changelog.outputs.latestVersion }}" == "1.0.0" ]]; then
              echo "BINARY_NAME=vc3_alx"
            else
              echo "BINARY_NAME=vc3_alx_final"
            fi
          ) >> $GITHUB_OUTPUT
#      - name: Create a release
#        uses: ncipollo/release-action@v1
#        with:
#          name: ${GITHUB_REPOSITORY#*/} ${tag#v}
#          body: |
#            Challenge version.
#          generateReleaseNotes: true
#          allowUpdates: true
#          artifactErrorsFailBuild: true
#          artifacts: "vc3_alx"