---

name: release
on:    # yamllint disable-line rule:truthy
  - push
permissions:
  contents: write
jobs:

  release:
    name: Make/Update a release from push
    runs-on: ubuntu-latest
    outputs:
      BINARY_NAME: ${{ steps.variables.outputs.BINARY_NAME }}
    steps:
      - name: Pause until all workflows are completed
        uses: willgarcia/workflow-wait-action@main
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parse Changelog
        id: changelog
        uses: ocavue/changelog-parser-action@v1
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-test-push.yml
          name: vc3_new_binary
      - name: Set up binary name based on a release version
        run: |
          (
            if [[ "${{ steps.changelog.outputs.latestVersion }}" == "1.0.0" ]]; then
              echo "BINARY_NAME=vc3_alx"
            else
              echo "BINARY_NAME=vc3_alx_final"
            fi
          ) >> $GITHUB_ENV
      - name: Replace an old binary
        run: |
          echo "$BINARY_NAME"
          ls -lh
          chmod +x vc3_new
          rm "$BINARY_NAME" || true
          mv vc3_new "$BINARY_NAME"
#      - name: Create a release
#        uses: ncipollo/release-action@v1
#        with:
#          name: ${GITHUB_REPOSITORY#*/} ${tag#v}
#          body: |
#            Challenge version.
#          generateReleaseNotes: true
#          allowUpdates: true
#          artifactErrorsFailBuild: true
#          artifacts: "vc3_alx"